### ISSUE TITLE
error occurred when migrate wordpress exported xml files

### ISSUE THREAD

**Issue by ghosrt** [hexojs/hexo-migrator-wordpress#1]
using node.js v0.10.26 on Windows 8.1 Pro, all settings by default

here's the log:

```
[error] TypeError: Cannot read property '1' of null
TypeError: Cannot read property '1' of null 
at ELEMENTS.replacement (D:\node.js\hexo\node_modules\hexo-migrator-wordpress\node_modules\to-markdown\src\to-markdown.js:71:70)
at D:\node.js\hexo\node_modules\hexo-migrator-wordpress\node_modules\to-markdown\src\to-markdown.js:96:41
at String.replace (native)
at replaceEls (D:\node.js\hexo\node_modules\hexo-migrator-wordpress\node_modules\to-markdown\src\to-markdown.js:95:23)
at toMarkdown (D:\node.js\hexo\node_modules\hexo-migrator-wordpress\node_modules\to-markdown\src\to-markdown.js:78:16)
at D:\node.js\hexo\node_modules\hexo-migrator-wordpress\index.js:59:54
at D:\node.js\hexo\node_modules\hexo-migrator-wordpress\node_modules\async\lib\async.js:111:13
at Array.forEach (native)
at _each (D:\node.js\hexo\node_modules\hexo-migrator-wordpress\node_modules\async\lib\async.js:32:24)
at Object.async.each (D:\node.js\hexo\node_modules\hexo-migrator-wordpress\node_modules\async\lib\async.js:110:9)
```

I have no idea about how to deal with it.

**Comment by miibotree** [comment]
have you fix the bug yet?@tommy351, it seems that the bug still exists

**Comment by SunnyBingoMe** [comment]
Same problem,   hexo-migrator-wordpress version 0.1.2. Windows 10.

**Comment by zhuziyi1989** [comment]
@SunnyBingoMe 谢谢~

**Comment by SunnyBingoMe** [comment]
@zhuziyi1989 客气
