### ISSUE TITLE
xml文件路径问题

### ISSUE THREAD

**Issue by MerlinFeng** [hexojs/hexo-migrator-wordpress#23]
hexo migrate wordpress /data/wwwroot/wordpress.xml 
INFO  Analyzing /data/wwwroot/wordpress.xml...
/data/wwwroot/hexo-site/node_modules/.0.1.2@hexo-migrator-wordpress/index.js:35
          if (err) throw err;
                   ^

Error: Invalid URI "/data/wwwroot/wordpress.xml"
    at Request.init (/data/wwwroot/hexo-site/node_modules/.2.81.0@request/request.js:276:31)
    at new Request (/data/wwwroot/hexo-site/node_modules/.2.81.0@request/request.js:130:8)
    at request (/data/wwwroot/hexo-site/node_modules/.2.81.0@request/index.js:54:10)
    at /data/wwwroot/hexo-site/node_modules/.0.1.2@hexo-migrator-wordpress/index.js:34:9
    at fn (/data/wwwroot/hexo-site/node_modules/.0.9.2@async/lib/async.js:638:34)
    at Immediate._onImmediate (/data/wwwroot/hexo-site/node_modules/.0.9.2@async/lib/async.js:554:34)
    at processImmediate [as _immediateCallback] (timers.js:383:17)

mv /data/wwwroot/wordpress.xml .

再次执行成功

**Comment by NoahDragon** [comment]
执行成功了？

**Comment by MerlinFeng** [comment]
@NoahDragon 是的 执行目录在当前文件夹下 就ok了 把xml文件放到的hexo根目录

**Comment by NoahDragon** [comment]
好的，那先关闭这个issue了。如果仍有问题可重开。
