### ISSUE TITLE
program crash in manjaro  linux 

### ISSUE THREAD

**Issue by 111qqz** [hexojs/hexo-migrator-wordpress#27]
/home/coder/blog/node_modules/to-markdown/src/to-markdown.js:71
        return '![' + (alt && alt[1] ? alt[1] : '') + ']' + '(' + src[1] + (title && title[1] ? ' "' + title[1] + '"' : '') + ')';
                                                                     ^

TypeError: Cannot read property '1' of null
    at replacement (/home/coder/blog/node_modules/to-markdown/src/to-markdown.js:71:70)
    at /home/coder/blog/node_modules/to-markdown/src/to-markdown.js:96:41
    at String.replace (<anonymous>)
    at replaceEls (/home/coder/blog/node_modules/to-markdown/src/to-markdown.js:95:23)
    at toMarkdown (/home/coder/blog/node_modules/to-markdown/src/to-markdown.js:78:16)
    at /home/coder/blog/node_modules/hexo-migrator-wordpress/index.js:68:19
    at /home/coder/blog/node_modules/hexo-migrator-wordpress/node_modules/async/lib/async.js:122:13
    at _each (/home/coder/blog/node_modules/hexo-migrator-wordpress/node_modules/async/lib/async.js:46:13)
    at Object.async.each (/home/coder/blog/node_modules/hexo-migrator-wordpress/node_modules/async/lib/async.js:121:9)
    at /home/coder/blog/node_modules/hexo-migrator-wordpress/index.js:48:13
    at fn (/home/coder/blog/node_modules/hexo-migrator-wordpress/node_modules/async/lib/async.js:638:34)
    at Immediate.<anonymous> (/home/coder/blog/node_modules/hexo-migrator-wordpress/node_modules/async/lib/async.js:554:34)
    at runCallback (timers.js:763:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate (timers.js:716:5)

**Comment by 111qqz** [comment]
I guess the reason is not checking empty value for src, I replace 'src[1]' with '(src &&src[1]?src[1]:'')' and it just works.

**Comment by bokeyy** [comment]
The same issue. Updating to-markdown to turndown fixes it.
See https://github.com/hexojs/hexo-migrator-wordpress/pull/28/commits/6399b8a05ee58de27709d5e29ef8df443b0c271c
