### ISSUE TITLE
why not successfull ?

### ISSUE THREAD

**Issue by dazuiba008** [hexojs/hexo-migrator-wordpress#31]
hexo migrate wordpress blog.xml 
INFO  Analyzing blog.xml...
/Users/zhanghaihong/myblog/blog/node_modules/hexo-migrator-wordpress/index.js:53
      async.each(xml.rss.channel[0].item, function(item, next){
                         ^

TypeError: Cannot read property 'channel' of undefined
    at /Users/zhanghaihong/myblog/blog/node_modules/hexo-migrator-wordpress/index.js:53:26
    at fn (/Users/zhanghaihong/myblog/blog/node_modules/hexo-migrator-wordpress/node_modules/async/lib/async.js:638:34)
    at Immediate._onImmediate (/Users/zhanghaihong/myblog/blog/node_modules/hexo-migrator-wordpress/node_modules/async/lib/async.js:554:34)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)

**Comment by tomap** [comment]
Hi, could you provide your RSS? Maybe it's invalid or ...?

**Comment by dwliu** [comment]
@tomap I got the same error as OP where it couldn't read property "channel"... fyi here is my blog RSS (I used 163 instead of WordPress though) http://www.blog.163.com/lybra1984/rss/. Also I am not so sure if it is still valid, as the blog service is to be shut down by end of the year.

**Comment by curbengh** [comment]
No longer applies after major refactor https://github.com/hexojs/hexo-migrator-wordpress/pull/57.
