### ISSUE TITLE
ERROR Plugin load failed

### ISSUE THREAD

**Issue by jashsayani** [hexojs/hexo-migrator-wordpress#32]
I am trying to migrate my Wordpress blog to hexo. I exported the `WordPress eXtended RSS file` from my blog and ran: `hexo migrate wordpress exported_file.xml`.

I see:
```
ERROR Plugin load failed: hexo-renderer-marked
Error: EISDIR: illegal operation on a directory, read
ERROR Plugin load failed: hexo-server
Error: EISDIR: illegal operation on a directory, read
ERROR Plugin load failed: hexo-renderer-stylus
Error: EISDIR: illegal operation on a directory, read
INFO Analyzing exported_file.xml...
…
```

--
hexo@3.8.0
hexo-migrator-wordpress@1.0.0

**Comment by adnan360** [comment]
I'm on Void Linux x86_64. I'm getting a different error.

Versions:
- npm: 6.14.5
- node: v13.2.0
- hexo-cli@3.1.0 [Global]
- hexo@4.2.1 [Local]
- hexo-migrator-wordpress@2.0.0 [Local]

```
cd /tmp
wget https://github.com/hexojs/hexo-migrator-wordpress/files/4836745/test.WordPress.2020-06-26.xml.zip
unzip test.WordPress.2020-06-26.xml.zip
hexo init hexotest
cd hexotest
npm install
npm install hexo-migrator-wordpress --save
hexo migrate wordpress ../test.WordPress.2020-06-26.xml
```

This shows:
```
ERROR Plugin load failed: hexo-migrator-wordpress
Error: No valid exports main found for '/tmp/hexotest/node_modules/camaro'
    at resolveExportsTarget (internal/modules/cjs/loader.js:611:9)
    at applyExports (internal/modules/cjs/loader.js:492:14)
    at resolveExports (internal/modules/cjs/loader.js:541:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:643:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:941:27)
    at Function.Module._load (internal/modules/cjs/loader.js:847:27)
    at Module.require (internal/modules/cjs/loader.js:1016:19)
    at require (internal/modules/cjs/helpers.js:69:18)
    at Object.<anonymous> (/tmp/hexotest/node_modules/hexo-migrator-wordpress/lib/feed.js:9:23)
    at Module._compile (internal/modules/cjs/loader.js:1121:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1160:10)
    at Module.load (internal/modules/cjs/loader.js:976:32)
    at Function.Module._load (internal/modules/cjs/loader.js:884:14)
    at Module.require (internal/modules/cjs/loader.js:1016:19)
    at require (internal/modules/cjs/helpers.js:69:18)
    at Object.<anonymous> (/tmp/hexotest/node_modules/hexo-migrator-wordpress/lib/migrator.js:7:19)
    at Module._compile (internal/modules/cjs/loader.js:1121:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1160:10)
    at Module.load (internal/modules/cjs/loader.js:976:32)
    at Function.Module._load (internal/modules/cjs/loader.js:884:14)
    at Module.require (internal/modules/cjs/loader.js:1016:19)
    at require (/tmp/hexotest/node_modules/hexo/lib/hexo/index.js:280:23)
undefined migrator plugin is not installed.

Installed migrator plugins:
  

For more help, you can check the online docs: https://hexo.io/
```

Running `npm i` did not help.

**Comment by adnan360** [comment]
I found a similar [error message on this issue](https://github.com/rollup/rollup/issues/3427) on another project named Rollup. It seems upgrading to at least `13.8.0` is necessary for it to work:

> I am sorry about this, this is specific to Node version 13.0.x - 13.7.x. Rollup is using conditional exports to support being used as an ES module in Node. The easiest solution is to update to at least Node 13.8.x. Node 12.x will work as well. ...

After installing Node.js 14.4.0 from tar.xz available from node website it worked. No errors given.

**Comment by SukkaW** [comment]
@adnan360 Thanks for pointing out this! We would take a look at `camero` then.

**Comment by curbengh** [comment]
We could drop Node 13.0 - 13.7, `">=12.13.0 <13.0.0 || >=13.8.0"`, but since Node 13 is already EOL, we might as well drop it altogether `">=12.13.0 <13 || >=14"`.

**Comment by curbengh** [comment]
Closing this as I noticed the plugin loads fine for OP
https://github.com/hexojs/hexo-migrator-wordpress/issues/101#issue-688460653
