### ISSUE TITLE
TypeError: Cannot read property 'domain' of undefined

### ISSUE THREAD

**Issue by congwang** [hexojs/hexo-migrator-wordpress#4]
TypeError: Cannot read property 'domain' of undefined
    at /home/wangcong/project/test/node_modules/hexo-migrator-wordpress/index.js:76:31
    at Array.forEach (native)
    at /home/wangcong/project/test/node_modules/hexo-migrator-wordpress/index.js:73:25
    at /home/wangcong/project/test/node_modules/hexo-migrator-wordpress/node_modules/async/lib/async.js:118:13
    at Array.forEach (native)
    at _each (/home/wangcong/project/test/node_modules/hexo-migrator-wordpress/node_modules/async/lib/async.js:39:24)
    at Object.async.each (/home/wangcong/project/test/node_modules/hexo-migrator-wordpress/node_modules/async/lib/async.js:117:9)
    at /home/wangcong/project/test/node_modules/hexo-migrator-wordpress/index.js:49:13
    at fn (/home/wangcong/project/test/node_modules/hexo-migrator-wordpress/node_modules/async/lib/async.js:626:34)
    at Object._onImmediate (/home/wangcong/project/test/node_modules/hexo-migrator-wordpress/node_modules/async/lib/async.js:542:34)[39m

**Comment by kfranqueiro** [comment]
I receive this error as well.  I suspect it is because there is an initial `category` tag in each `item` that has no attributes whatsoever.

Example:

```xml
		<category><![CDATA[JavaScript]]></category>
		<category domain="category" nicename="js"><![CDATA[JavaScript]]></category>
		<category domain="tag"><![CDATA[javascript]]></category>
		<category domain="tag" nicename="javascript-2"><![CDATA[javascript]]></category>
```

**Comment by ezy** [comment]
For anyone who isn't clear on the fix for this - it's to remove all instances of `<category>` xml tags without a domain. Then run your import and it should work as expected.

**Comment by curbengh** [comment]
v2.1.0 ignores `<category>` without domain attribute.
https://github.com/hexojs/hexo-migrator-wordpress/blob/e3d96c6e14d13c06add80e4d9f6d9e242cce8cff/lib/feed.js#L25
https://github.com/hexojs/hexo-migrator-wordpress/pull/89
