### ISSUE TITLE
When I migrated when it seems there is a problem.

### ISSUE THREAD

**Issue by netcan** [hexojs/hexo-migrator-wordpress#9]
When I migrated when it seems there is a problem.

**Comment by netcan** [comment]
``
/home/netcan/WorkSpace/Netcan_Web/netcan_blog/node_modules/hexo-migrator-wordpress/node_modules/to-markdown/src/to-markdown.js:71
       return '![' + (alt && alt[1] ? alt[1] : '') + ']' + '(' + src[1] + (tit
                                                                    ^
TypeError: Cannot read property '1' of null
    at ELEMENTS.replacement (/home/netcan/WorkSpace/Netcan_Web/netcan_blog/node_modules/hexo-migrator-wordpress/node_modules/to-markdown/src/to-markdown.js:71:70)
    at /home/netcan/WorkSpace/Netcan_Web/netcan_blog/node_modules/hexo-migrator-wordpress/node_modules/to-markdown/src/to-markdown.js:96:41
    at String.replace (native)
    at replaceEls (/home/netcan/WorkSpace/Netcan_Web/netcan_blog/node_modules/hexo-migrator-wordpress/node_modules/to-markdown/src/to-markdown.js:95:23)
    at toMarkdown (/home/netcan/WorkSpace/Netcan_Web/netcan_blog/node_modules/hexo-migrator-wordpress/node_modules/to-markdown/src/to-markdown.js:78:16)
    at /home/netcan/WorkSpace/Netcan_Web/netcan_blog/node_modules/hexo-migrator-wordpress/index.js:68:19
    at /home/netcan/WorkSpace/Netcan_Web/netcan_blog/node_modules/hexo-migrator-wordpress/node_modules/async/lib/async.js:122:13
    at _each (/home/netcan/WorkSpace/Netcan_Web/netcan_blog/node_modules/hexo-migrator-wordpress/node_modules/async/lib/async.js:46:13)
    at Object.async.each (/home/netcan/WorkSpace/Netcan_Web/netcan_blog/node_modules/hexo-migrator-wordpress/node_modules/async/lib/async.js:121:9)
    at /home/netcan/WorkSpace/Netcan_Web/netcan_blog/node_modules/hexo-migrator-wordpress/index.js:48:13
    at fn (/home/netcan/WorkSpace/Netcan_Web/netcan_blog/node_modules/hexo-migrator-wordpress/node_modules/async/lib/async.js:638:34)
    at Immediate._onImmediate (/home/netcan/WorkSpace/Netcan_Web/netcan_blog/node_modules/hexo-migrator-wordpress/node_modules/async/lib/async.js:554:34)
    at processImmediate [as _immediateCallback] (timers.js:358:17)
``

**Comment by netcan** [comment]
``
/home/netcan/WorkSpace/Netcan_Web/netcan_blog/node_modules/hexo-migrator-wordpress/node_modules/to-markdown/src/to-markdown.js:71
       return '![' + (alt && alt[1] ? alt[1] : '') + ']' + '(' + src[1] + (tit
                                                                    ^
TypeError: Cannot read property '1' of null
    at ELEMENTS.replacement (/home/netcan/WorkSpace/Netcan_Web/netcan_blog/node_modules/hexo-migrator-wordpress/node_modules/to-markdown/src/to-markdown.js:71:70)
    at /home/netcan/WorkSpace/Netcan_Web/netcan_blog/node_modules/hexo-migrator-wordpress/node_modules/to-markdown/src/to-markdown.js:96:41
    at String.replace (native)
    at replaceEls (/home/netcan/WorkSpace/Netcan_Web/netcan_blog/node_modules/hexo-migrator-wordpress/node_modules/to-markdown/src/to-markdown.js:95:23)
    at toMarkdown (/home/netcan/WorkSpace/Netcan_Web/netcan_blog/node_modules/hexo-migrator-wordpress/node_modules/to-markdown/src/to-markdown.js:78:16)
    at /home/netcan/WorkSpace/Netcan_Web/netcan_blog/node_modules/hexo-migrator-wordpress/index.js:68:19
    at /home/netcan/WorkSpace/Netcan_Web/netcan_blog/node_modules/hexo-migrator-wordpress/node_modules/async/lib/async.js:122:13
    at _each (/home/netcan/WorkSpace/Netcan_Web/netcan_blog/node_modules/hexo-migrator-wordpress/node_modules/async/lib/async.js:46:13)
    at Object.async.each (/home/netcan/WorkSpace/Netcan_Web/netcan_blog/node_modules/hexo-migrator-wordpress/node_modules/async/lib/async.js:121:9)
    at /home/netcan/WorkSpace/Netcan_Web/netcan_blog/node_modules/hexo-migrator-wordpress/index.js:48:13
    at fn (/home/netcan/WorkSpace/Netcan_Web/netcan_blog/node_modules/hexo-migrator-wordpress/node_modules/async/lib/async.js:638:34)
    at Immediate._onImmediate (/home/netcan/WorkSpace/Netcan_Web/netcan_blog/node_modules/hexo-migrator-wordpress/node_modules/async/lib/async.js:554:34)
    at processImmediate [as _immediateCallback] (timers.js:358:17)
``

**Comment by netcan** [comment]
```
/home/netcan/WorkSpace/Netcan_Web/netcan_blog/node_modules/hexo-migrator-wordpress/node_modules/to-markdown/src/to-markdown.js:71
       return '![' + (alt && alt[1] ? alt[1] : '') + ']' + '(' + src[1] + (tit
                                                                    ^
TypeError: Cannot read property '1' of null
    at ELEMENTS.replacement (/home/netcan/WorkSpace/Netcan_Web/netcan_blog/node_modules/hexo-migrator-wordpress/node_modules/to-markdown/src/to-markdown.js:71:70)
    at /home/netcan/WorkSpace/Netcan_Web/netcan_blog/node_modules/hexo-migrator-wordpress/node_modules/to-markdown/src/to-markdown.js:96:41
    at String.replace (native)
    at replaceEls (/home/netcan/WorkSpace/Netcan_Web/netcan_blog/node_modules/hexo-migrator-wordpress/node_modules/to-markdown/src/to-markdown.js:95:23)
    at toMarkdown (/home/netcan/WorkSpace/Netcan_Web/netcan_blog/node_modules/hexo-migrator-wordpress/node_modules/to-markdown/src/to-markdown.js:78:16)
    at /home/netcan/WorkSpace/Netcan_Web/netcan_blog/node_modules/hexo-migrator-wordpress/index.js:68:19
    at /home/netcan/WorkSpace/Netcan_Web/netcan_blog/node_modules/hexo-migrator-wordpress/node_modules/async/lib/async.js:122:13
    at _each (/home/netcan/WorkSpace/Netcan_Web/netcan_blog/node_modules/hexo-migrator-wordpress/node_modules/async/lib/async.js:46:13)
    at Object.async.each (/home/netcan/WorkSpace/Netcan_Web/netcan_blog/node_modules/hexo-migrator-wordpress/node_modules/async/lib/async.js:121:9)
    at /home/netcan/WorkSpace/Netcan_Web/netcan_blog/node_modules/hexo-migrator-wordpress/index.js:48:13
    at fn (/home/netcan/WorkSpace/Netcan_Web/netcan_blog/node_modules/hexo-migrator-wordpress/node_modules/async/lib/async.js:638:34)
    at Immediate._onImmediate (/home/netcan/WorkSpace/Netcan_Web/netcan_blog/node_modules/hexo-migrator-wordpress/node_modules/async/lib/async.js:554:34)
    at processImmediate [as _immediateCallback] (timers.js:358:17)
```

**Comment by SunnyBingoMe** [comment]
is this the same with #1 ?

**Comment by netcan** [comment]
yes, I think my wordpress posts don't standard. It is format confusion.
